# Generated by Django 5.2.2 on 2025-06-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_draft',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], max_length=15),
        ),
    ]
