# Generated by Django 5.2.2 on 2025-06-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_draft',
            field=models.CharField(choices=[('False', 'Draft'), ('True', 'Published')], default='True', max_length=15),
        ),
    ]
