# Generated by Django 5.2.2 on 2025-06-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_alter_post_is_draft"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postlike",
            name="like_count",
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
    ]
